apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090  # URL of the Prometheus service, within the Docker network
    isDefault: true
    editable: true

