{
 "title": "Grafango",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Core Usage %",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 1 },
   "targets": [
    { "expr": "system_cpu_core_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 15 },
   "targets": [
    { "expr": "system_cpu_usage_percent", "legendFormat": "__auto" }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Memory Usage %",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
   "targets": [
    { "expr": "system_memory_usage_percent", "legendFormat": "__auto" },
    {}
   ]
  },
  {
   "title": "Memory Total Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    { "expr": "system_memory_total_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Available Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    { "expr": "system_memory_available_bytes", "legendFormat": "__auto" }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Disk Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    { "expr": "system_disk_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk Total Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "targets": [
    { "expr": "system_disk_total_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}